var fs = require('fs');
var parse = require('csv-parse');

var country_list = ['AFGHANISTAN', 'ALBANIA', 'ALGERIA', 'ANDORRA', 'ANGOLA', 'ANGUILLA', 'ANTARCTIC FISHERIES', 'ANTIGUA & BARBUDA', 'ARGENTINA', 'ARMENIA', 'ARUBA', 'AUSTRALIA', 'AUSTRIA', 'AZERBAIJAN', 'BAHAMAS', 'BAHRAIN', 'BANGLADESH', 'BARBADOS', 'BELARUS', 'BELGIUM', 'BELIZE', 'BENIN', 'BERMUDA', 'BHUTAN', 'BONAIRE, SAINT EUSTATIUS, AND SABA', 'BOSNIA & HERZEGOVINA', 'BOTSWANA', 'BRAZIL', 'BRITISH VIRGIN ISLANDS', 'BRUNEI (DARUSSALAM)', 'BULGARIA', 'BURKINA FASO', 'BURUNDI', 'CAMBODIA', 'CANADA', 'CAPE VERDE', 'CAYMAN ISLANDS', 'CENTRAL AFRICAN REPUBLIC', 'CHAD', 'CHILE', 'CHINA (MAINLAND)', 'CHRISTMAS ISLAND', 'COLOMBIA', 'COMOROS', 'CONGO', 'COOK ISLANDS', 'COSTA RICA', 'COTE D IVOIRE', 'CROATIA', 'CUBA', 'CURACAO', 'CYPRUS', 'CZECH REPUBLIC', 'CZECHOSLOVAKIA', 'DEMOCRATIC PEOPLE S REPUBLIC OF KOREA', 'DEMOCRATIC REPUBLIC OF THE CONGO (FORMERLY ZAIRE)', 'DEMOCRATIC REPUBLIC OF VIETNAM', 'DENMARK', 'DJIBOUTI', 'DOMINICA', 'DOMINICAN REPUBLIC', 'EAST & WEST PAKISTAN', 'ECUADOR', 'EGYPT', 'EL SALVADOR', 'EQUATORIAL GUINEA', 'ERITREA', 'ESTONIA', 'ETHIOPIA', 'FAEROE ISLANDS', 'FALKLAND ISLANDS (MALVINAS)', 'FEDERAL REPUBLIC OF GERMANY', 'FEDERATED STATES OF MICRONESIA', 'FEDERATION OF MALAYA-SINGAPORE', 'FIJI', 'FINLAND', 'FORMER DEMOCRATIC YEMEN', 'FORMER GERMAN DEMOCRATIC REPUBLIC', 'FORMER PANAMA CANAL ZONE', 'FORMER YEMEN', 'FRANCE (INCLUDING MONACO)', 'FRENCH EQUATORIAL AFRICA', 'FRENCH GUIANA', 'FRENCH INDO-CHINA', 'FRENCH POLYNESIA', 'FRENCH WEST AFRICA', 'GABON', 'GAMBIA', 'GEORGIA', 'GERMANY', 'GHANA', 'GIBRALTAR', 'GREECE', 'GREENLAND', 'GRENADA', 'GUADELOUPE', 'GUATEMALA', 'GUINEA', 'GUINEA BISSAU', 'GUYANA', 'HAITI', 'HONDURAS', 'HONG KONG SPECIAL ADMINSTRATIVE REGION OF CHINA', 'HUNGARY', 'ICELAND', 'INDIA', 'INDONESIA', 'IRAQ', 'IRELAND', 'ISLAMIC REPUBLIC OF IRAN', 'ISRAEL', 'ITALY (INCLUDING SAN MARINO)', 'JAMAICA', 'JAPAN', 'JAPAN (EXCLUDING THE RUYUKU ISLANDS)', 'JORDAN', 'KAZAKHSTAN', 'KENYA', 'KIRIBATI', 'KUWAIT', 'KUWAITI OIL FIRES', 'KYRGYZSTAN', 'LAO PEOPLE S DEMOCRATIC REPUBLIC', 'LATVIA', 'LEBANON', 'LEEWARD ISLANDS', 'LESOTHO', 'LIBERIA', 'LIBYAN ARAB JAMAHIRIYAH', 'LIECHTENSTEIN', 'LITHUANIA', 'LUXEMBOURG', 'MACAU SPECIAL ADMINSTRATIVE REGION OF CHINA', 'MACEDONIA', 'MADAGASCAR', 'MALAWI', 'MALAYSIA', 'MALDIVES', 'MALI', 'MALTA', 'MARSHALL ISLANDS', 'MARTINIQUE', 'MAURITANIA', 'MAURITIUS', 'MEXICO', 'MONGOLIA', 'MONTENEGRO', 'MONTSERRAT', 'MOROCCO', 'MOZAMBIQUE', 'MYANMAR (FORMERLY BURMA)', 'NAMIBIA', 'NAURU', 'NEPAL', 'NETHERLAND ANTILLES', 'NETHERLAND ANTILLES AND ARUBA', 'NETHERLANDS', 'NEW CALEDONIA', 'NEW ZEALAND', 'NICARAGUA', 'NIGER', 'NIGERIA', 'NIUE', 'NORWAY', 'OCCUPIED PALESTINIAN TERRITORY', 'OMAN', 'PACIFIC ISLANDS (PALAU)', 'PAKISTAN', 'PALAU', 'PANAMA', 'PAPUA NEW GUINEA', 'PARAGUAY', 'PENINSULAR MALAYSIA', 'PERU', 'PHILIPPINES', 'PLURINATIONAL STATE OF BOLIVIA', 'POLAND', 'PORTUGAL', 'PUERTO RICO', 'QATAR', 'REPUBLIC OF CAMEROON', 'REPUBLIC OF KOREA', 'REPUBLIC OF MOLDOVA', 'REPUBLIC OF SOUTH SUDAN', 'REPUBLIC OF SOUTH VIETNAM', 'REPUBLIC OF SUDAN', 'REUNION', 'RHODESIA-NYASALAND', 'ROMANIA', 'RUSSIAN FEDERATION', 'RWANDA', 'RWANDA-URUNDI', 'RYUKYU ISLANDS', 'SABAH', 'SAINT HELENA', 'SAINT LUCIA', 'SAINT MARTIN (DUTCH PORTION)', 'SAMOA', 'SAO TOME & PRINCIPE', 'SARAWAK', 'SAUDI ARABIA', 'SENEGAL', 'SERBIA', 'SEYCHELLES', 'SIERRA LEONE', 'SINGAPORE', 'SLOVAKIA', 'SLOVENIA', 'SOLOMON ISLANDS', 'SOMALIA', 'SOUTH AFRICA', 'SPAIN', 'SRI LANKA', 'ST. KITTS-NEVIS', 'ST. KITTS-NEVIS-ANGUILLA', 'ST. PIERRE & MIQUELON', 'ST. VINCENT & THE GRENADINES', 'SUDAN', 'SURINAME', 'SWAZILAND', 'SWEDEN', 'SWITZERLAND', 'SYRIAN ARAB REPUBLIC', 'TAIWAN', 'TAJIKISTAN', 'TANGANYIKA', 'THAILAND', 'TIMOR-LESTE (FORMERLY EAST TIMOR)', 'TOGO', 'TONGA', 'TRINIDAD AND TOBAGO', 'TUNISIA', 'TURKEY', 'TURKMENISTAN', 'TURKS AND CAICOS ISLANDS', 'TUVALU', 'UGANDA', 'UKRAINE', 'UNITED ARAB EMIRATES', 'UNITED KINGDOM', 'UNITED KOREA', 'UNITED REPUBLIC OF TANZANIA', 'UNITED STATES OF AMERICA', 'URUGUAY', 'USSR', 'UZBEKISTAN', 'VANUATU', 'VENEZUELA', 'VIET NAM', 'WALLIS AND FUTUNA ISLANDS', 'YEMEN', 'YUGOSLAVIA (FORMER SOCIALIST FEDERAL REPUBLIC)', 'YUGOSLAVIA (MONTENEGRO & SERBIA)', 'ZAMBIA', 'ZANZIBAR', 'ZIMBABWE'];

fs.readFile('countries.csv', 'utf8', function (err, data) {
	if (err) throw err;

	//read csv
	parse(data, {columns: true, trim: true}, function(err, rows) {
		
		//make new object with key = year & value = emissions data
		var reformatted_data = {};

		for (var i = 1850; i >= 1850 && i <= 2014; i++) {
			reformatted_data[i] = {};
			country_list.forEach(function (country) {
				reformatted_data[i][country] = 0;
			});
		}

		// loop through json arry to get above
		rows.forEach(function (row){
			var country = row.Nation;
			var year = +row.Year;
			var emissions = +row.Total_emissions;
			if (year >= 1850) {
				reformatted_data[year][country] = emissions;
			}
		});

		//reformat for v4 stack
		var new_data = [];

		Object.keys(reformatted_data).forEach(function (year) {
			reformatted_data[year]['year'] = year;

			new_data.push(reformatted_data[year])
		})
		console.log(new_data)
		

		fs.writeFileSync('new_data_v4.json', JSON.stringify(new_data), 'utf8')	
    })

})
